# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 
  inhibit_all_warnings!
  pod 'MQTTClient'
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'SDWebImage', '~> 4.0'
  pod 'YYKit'

  # Pods for MyChat

end
